### ISSUE TITLE
No funciona con Wildfly 8.x

### ISSUE THREAD

**Issue by villadiegofj** [villadiegofj/contenedor-01#1]
Al usar un servidor Wildfly 8.x embebido la aplicacion no logra cargar las librerias de este.

**Comment by frankyjose** [comment]
He probado con Wildfly 9.0 y funciona perfecto. Debe haber algun tema en particualar con Wildlfly 8.x. Tal vez alguien con una imagen para reproducir bien el problema?

![testbug](https://cloud.githubusercontent.com/assets/2013641/9822931/e97185a2-5888-11e5-9000-85022da7958c.png)

Lo que vemos son los Listener que no encuentran las librerias de Wildlfly embebido. Hay que mover unos jar y listo.

**Comment by villadiegofj** [comment]
Gracias a todos por las respuestas!!
